<footer>
    <p>Sistema de control de gastos Versión 1.0</p>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?php echo APP_URL; ?>views/layouts/default/js/vendor/modernizr-2.8.3.min.js"><\/script>')</script>
        <script src="<?php echo APP_URL; ?>views/layouts/default/js/vendor/modernizr-2.8.3.min.js"></script>
        <script src="<?php echo APP_URL; ?>views/layouts/default/js/vendor/modernizr-2.8.3.min.js"></script>
        <script src="<?php echo APP_URL; ?>views/layouts/default/js/vendor/modernizr-2.8.3.min.js"></script>
</footer>
</div>
</body>
</html>